ENH: Modify train to accept checkpoints
vocalpy/vak pull request #505
Opened 2022-04-22 17:48 UTC by kaiyaprovost

2022-04-23 14:11 UTC, NickleDave commented
:tada: excellent, thank you @kaiyaprovost 

Will review this and get you feedback by the end of Monday

2022-04-23 15:25 UTC, NickleDave commented on src/vak/core/train.py
> +        spect_standardizer = None
I think there's an indentation error here?

When I try to run I get 
```python
src/vak/core/learncurve/learncurve.py:8: in <module>
    from ..train import train
E     File "/home/pimienta/Documents/repos/coding/vocal/vak/src/vak/core/train.py", line 215
E       spect_standardizer = joblib.load(spect_scaler_path)
E       ^
E   IndentationError: unexpected indent
```

(the `E`s are because I'm running with `pytest`)

2022-04-23 15:50 UTC, NickleDave requested changes

2022-04-23 15:50 UTC, NickleDave commented on src/vak/core/train.py
> +            f"not using a spect scaler",
I think this log message could confuse someone who is using `train` *without* loading a checkpoint, if they have set `normalize_spectrograms` to `true` in the config file.  
They will still be using a `spect_scaler`, it will just be a new one fit to the data

I'd suggest changing it to something like `"No spect_scaler_path not provided, not loading"`

2022-04-23 15:50 UTC, NickleDave commented on src/vak/core/train.py
> +        spect_standardizer = None
Seems like there might be a possible control flow bug here?  

We set `spect_standardizer` to `None` but then in the next code block we will overwrite that if `normalize_spectrograms` is set to `True`

When I look at the code in PyCharm this line is greyed out.  
Usually that indicates the variable is not used, but in this case it's because the `spect_standardizer` that gets created here is clobbered by the one that gets created in the `if normalize_spectrograms ... else` code block

2022-04-23 15:50 UTC, NickleDave commented on src/vak/core/train.py
>      if normalize_spectrograms:
re: comment above on line 211

I think this line may needs to change to something like:
```
if normalize_spectrograms and spect_scaler_path is None
    ...
elif not normalize_spectograms and spect_scaler_path is None:
     spect_standardizer = None
```

There's multiple things interacting here I need to think more about. Will comment on the pull request itself.

2022-04-23 15:56 UTC, NickleDave commented
@kaiyaprovost two big picture things:

- Are you using an IDE like PyCharm or vscode? If not you might find it helpful, since they will usually spot issues like the indent error I commented on. I usually use PyCharm and find it to be a little friendlier even though many people like vscode.
- Are you able to run the tests locally? If not please let me know what I can do to help you set that up. I did try to document here how to set up an environment and get the data used for running  tests: https://vak.readthedocs.io/en/latest/development/contributors.html#setting-up-a-development-environment.  
  - You can run just the tests for the `vak.core.train` module by activating the virtual environment and then running `pytest tests/test_core/test_train.py` -- that can at least let you get quick feedback on whether the current functionality is still working after any changes you make, even if we haven't written new tests yet

2022-04-23 16:53 UTC, NickleDave requested changes

2022-04-23 16:53 UTC, NickleDave commented on src/vak/core/train.py
> +    if labelmap is not None:
Pretty sure this will cause an error because `labelmap` isn't defined yet

We probably want to do something like the following here:
```python
    if labelmap_path:
        log_or_print(
            f"loading labelmap from path: {labelmap_path}", logger=logger, level="info"
        )
        with labelmap_path.open("r") as f:
            labelmap = json.load(f)
    else: 
        labelmap = labels.to_map(labelset, map_unlabeled=map_unlabeled)
        log_or_print(
            f"number of classes in labelmap: {len(labelmap)}", logger=logger, level="info"
        )
        # save labelmap in case we need it later
        with open(results_path.joinpath("labelmap.json"), "w") as f:
            json.dump(labelmap, f)
```

2022-04-23 17:22 UTC, NickleDave commented
@kaiyaprovost I added some thoughts about `spect_scaler_path` on the original issue describing how we should implement:
https://github.com/vocalpy/vak/issues/5#issuecomment-1107537580 

Please reply there letting me know what you think and we can proceed once we agree.

One option would be just to implement the logic pretty much the way I describe and then we can both take it for a test drive.

2022-04-27 18:15 UTC, kaiyaprovost commented on src/vak/core/train.py
> +            f"not using a spect scaler",
Changed accordingly, will be included in next pull request

2022-04-27 18:18 UTC, kaiyaprovost commented on src/vak/core/train.py
> +        spect_standardizer = None
Fixed!

2022-04-27 18:20 UTC, kaiyaprovost commented on src/vak/core/train.py
>      if normalize_spectrograms:
Fixed!

2022-04-27 20:24 UTC, kaiyaprovost commented on src/vak/core/train.py
> +    if labelmap is not None:
Fixed!

2022-04-27 20:35 UTC, kaiyaprovost commented
I replied to the other thread re: the issue. I do not currently use PyCharm or vscode, I do all of my python programming in a regular text editor (bbedit). About to tackle getting the tests on my machine and will report back.

2022-04-28 19:56 UTC, NickleDave commented
Thank you @kaiyaprovost !!!

At first glance this looks like it addresses most of the requested changes.

Let me know how it goes with running tests.

I should have a chance to get you feedback on these changes by the end of this weekend.

2022-04-30 22:22 UTC, NickleDave commented on src/vak/core/train.py
> +        spect_standardizer = None
Fixed by [bf40764](https://github.com/vocalpy/vak/pull/505/commits/bf4076463a7065bf006d9ef41c81edfb2e8a40e2)

2022-04-30 22:27 UTC, NickleDave commented on src/vak/core/train.py
> +        spect_standardizer = None
Resolved by newer commits -- I think there might be a couple tweaks we can make but will make a new review

2022-04-30 22:28 UTC, NickleDave commented on src/vak/core/train.py
>      if normalize_spectrograms:
Fixed as per discussion on issue
https://github.com/vocalpy/vak/issues/5#issuecomment-1111454752

2022-04-30 22:28 UTC, NickleDave commented on src/vak/core/train.py
> +    if labelmap is not None:
Fixed by commits below

2022-04-30 22:29 UTC, NickleDave commented
Excellent! The tests are running now without any errors or failures, so we are making progress.  

I think there's still a couple tweaks we can make, will request a couple more changes

2022-04-30 22:53 UTC, NickleDave requested changes

2022-04-30 22:53 UTC, NickleDave commented on src/vak/core/train.py
> +    ## check if a labelmap already exists
I think I might be guilty of adding some of these comments but let's remove them -- in general it's preferable to write comments that explain *why* we did something (because it's not obvious from the code) but these read more like *what* comments to me, where it's fairly clear from the `if` statements what we're trying to do

2022-04-30 22:53 UTC, NickleDave commented on src/vak/core/train.py
> +    ## check if a spect scaler already exists
as above, let's remove this comment

2022-04-30 22:53 UTC, NickleDave commented on src/vak/core/train.py
> +        spect_standardizer = None
We set `spect_standardizer`  to `None` here but then immediately replace it in line 228

```python
        spect_standardizer = None
        # wordy comment here that we can probably remove
        spect_standardizer = transforms.StandardizeSpect.fit_df(
            dataset_df, spect_key=spect_key
        )
```

I think we can just remove the `spect_standardizer = None` line?

2022-04-30 22:53 UTC, NickleDave commented on src/vak/core/train.py
> +            f"no spect_scaler_path not provided, not loading",
Need to either remove "no" or "not" here -- double negative (legit in Spanish but might be confusing in English :slightly_smiling_face: )

2022-04-30 22:53 UTC, NickleDave commented on src/vak/core/train.py
> +        #not normalize_spectrograms and spect_scaler_path is None:
comment is ok here I think to make the implicit explicit

We should add a log statement though, something like:
```python
log_or_print(
    "normalize_spectrograms is False and no spect_scaler_path was provided, will not standardize spectrograms", 
    logger=logger, level="info")
```

2022-04-30 22:58 UTC, NickleDave commented
@kaiyaprovost I requested some more changes but these are mostly minor clean-ups; let me know what you think

After you address those comments, the next steps will be:
- squash the commits down, probably into one "ENH" commit that fixes the issue
- write some unit tests that make sure the new functionality works
- add some initial documentation

I am happy to handle any or all of that but I am also happy to walk you through it -- whichever you prefer.   
Might be good for you to learn how to squash the commits; figuring out how to write the tests might be more trouble than it's worth for you right now because there's a lot of `pytest` abstractions tied up in how they're written, and stuff that's specific to how I structured the tests, so getting up to speed could take a bit. Same for the docs. But again if you want to try I'm happy to teach you what I know.

Thank you for everything you've contributed so far

2022-05-26 21:37 UTC, NickleDave commented
Great, thank you @kaiyaprovost!  
And sorry I haven't gotten to this sooner.  

Just ran tests and everything is still passing.  
Will write a couple to test this new functionality and then merge in ASAP.

2022-05-27 14:59 UTC, NickleDave commented
@kaiyaprovost I made one last change so that when `spect_scaler_path` and `labelmap_path` are passed in as arguments, they are saved to the new `results_path`. 

So even though we may be continuing training, we always create a new directory `results_{timestamp}` and it always has a checkpoint path, labemap.json, and a spect scaler (if  it exists).

2022-05-27 15:02 UTC, NickleDave commented
@theresekoch heads up that this will change `vak.core.train` -- not sure if that is a function you are relying on directly -- but the added parameters will default to `None` so everything should work as before

2022-05-28 22:16 UTC, NickleDave approved these changes
"reviewing" after I made changes, so the "changes requested" goes away. 
All seems to be working now locally, just need CI to pass

2022-05-29 20:23 UTC, NickleDave commented
:tada: :rocket: This is passing! Going to merge in @kaiyaprovost! Thanks so much for contributing :pray: :pray: :pray: 

Test pass on Linux and on Mac Python 3.7 -- the CI times out on Mac after that but this is due to an existing issue

I will go ahead and release a version 0.5 in the next couple days so we can test "in the real world".  
I need to do a couple other maintenance things that I will cram into that release

2022-05-29 20:24 UTC, merged

2022-06-10 00:40 UTC, NickleDave commented
@all-contributors please add @kaiyaprovost for code and ideas

2022-06-10 00:43 UTC, NickleDave commented
@all-contributors please add @kaiyaprovost for code and ideas