Update README.md
vocalpy/vak pull request #551
Opened 2022-07-24 07:08 UTC by akn0717

Great work!
I help make some minor edits.

2022-07-26 13:37 UTC, NickleDave commented
Hi @akn0717, thank you for taking the time to make these minor edits.  

I'm happy to merge in the capitalization fixes but I prefer the sentence you changed the way it was originally written. I'll request a change.

2022-07-26 13:44 UTC, NickleDave requested changes

2022-07-26 13:44 UTC, NickleDave commented on README.md
> +Currently, the main use is an automatic annotation of vocalizations and other animal sounds. By annotation, we mean something like the example of annotated birdsong shown below:
Please put "annotation" in italics using single asterisks. The goal here is to define the technical meaning of the word.

See here
https://blogs.millersville.edu/bduncan/italics-quotation-marks-underscore/
> Use italics for emphasis, for unfamiliar foreign words and phrases, and for technical terms followed by definitions.

I had it in bold before but actually would prefer italics now that you draw attention to it.

2022-07-26 13:44 UTC, NickleDave commented on README.md
> +`vak` requires audio files or spectrogram files with annotations as the training data input, and `vak` will help you train and utilize your neural networks to make predicted annotations for new files
Please change this sentence back the way it was. The informal "you" here is intentional.

2022-07-26 20:26 UTC, akn0717 commented
Thank you for pointing out what you prefer!
I have made the changes as you requested.

2022-07-28 00:50 UTC, NickleDave approved these changes
LGTM!

2022-07-28 00:50 UTC, NickleDave commented
Looks great, thank you @akn0717

2022-07-28 00:51 UTC, merged

2022-07-28 00:51 UTC, NickleDave commented
@all-contributors please add @akn0717 for docs